Update README.md
petrucci34/iOS-test pull request #10
Opened 2021-01-31 05:46 UTC by korhan-square

2021-01-31 05:50 UTC, korhan-square commented
test

2021-01-31 05:50 UTC, korhan-square commented
test1

2021-02-01 03:53 UTC, petrucci34 commented
- [ ] one

2021-02-01 03:53 UTC, petrucci34 requested changes
- [x] one
- [x] two
- [ ] three

2021-02-01 03:54 UTC, closed without merging